openapi: 3.0.0
info:
  title: 'Transfer Request Management API'
  description: "Week 10's Assignment - Transfer Request Management API with Authentication & Authorization"
  version: 1.0.0

servers:
- url: http://localhost:5115
  description: Localhost Link for Development
- url: https://week10sherin-prod.up.railway.app/
  description: Live link for Production

paths:
  /:
    get:
      summary: Project Landing Page
      responses:
        '200':
          description: Successfully reached Project Landing Page
          content:
            application/json:
              example:
                success: true
                message: Hello, this is Sherin Olivia's Assignment for Week 10

  /api/transfers:
    get:
      summary: Get all transfer requests
      responses:
        '200':
          description: Transfer requests retrieved successfully
          content:
            application/json:
              example:
                message: Transfer Requests Successfully Retrieved
                data:
                  - _id: "64e69eecd9bfba9c379ce9af"
                    user_name: SH-Test
                    amount: 200000
                    purpose: Wealth Transfer P.2
                    status: Approved
                  - _id: "64e7dcc26983d9b0e21b781c"
                    user_name: adminRoo
                    amount: 2000
                    purpose: Parking Ticket
                    status: Pending
        '500':
          description: Internal server error
          content:
            application/json:
              example:
                error: An error occurred while retrieving transfer requests

  /api/transfers/new:
    post:
      summary: Create a new transfer request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_name:
                  type: string
                  description: Name of the user initiating the transfer
                amount:
                  type: number
                  format: float
                  description: Amount to be transferred
                purpose:
                  type: string
                  description: Purpose of the transfer
              required:
                - user_name
                - amount
                - purpose
      responses:
        '200':
          description: New transfer request created successfully
          content:
            application/json:
              example:
                message: New Transfer Request Successfully Created
                data:
                  _id: "64e7dcc26983d9b0e21b781c"
                  user_name: adminRoo
                  amount: 2000
                  purpose: Parking Ticket
                  status: Pending
        '500':
          description: Internal server error
          content:
            application/json:
              example:
                error: Transfer Request Failed - Internal Error

  /api/transfers/{_id}:
    patch:
      summary: Update transfer status
      parameters:
        - name: _id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the transfer request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                newStatus:
                  type: string
                  enum: [Approved, Rejected]
                  description: The new status for the transfer request
      responses:
        '200':
          description: Transfer request status updated successfully
          content:
            application/json:
              example:
                message: Transfer Request Status Updated Successfully..!
                data:
                  _id: "64e69eecd9bfba9c379ce9af"
                  status: Approved
        '400':
          description: Bad request or update failed
          content:
            application/json:
              example:
                error: Transfer Request status is not Pending..! Update Failed..!
        '404':
          description: Transfer request not found
          content:
            application/json:
              example:
                error: Transfer Request not found..!
        '500':
          description: Internal server error
          content:
            application/json:
              example:
                error: Transfer Request Status Update Failed..!
  
  /api/users:
    get:
      summary: Get all user data
      responses:
        '200':
          description: All User data retrieved successfully
          content:
            application/json:
              example:
                message: All User Data Successfully Retrieved
                data:
                  - _id: "5f8a5f7a4b56a6778c1a2345"
                    username: SH-Test
                    role: Maker

        '500':
          description: Internal server error
          content:
            application/json:
              example:
                error: An error occurred while retrieving user data

  /api/users/register:
    post:
        summary: Register New User
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                    minLength: 3
                    pattern: "^(?=.*[^\\s]).{3,}$"
                    description: User's username
                  password:
                    type: string
                    minLength: 8
                    pattern: "^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]+$"
                    description: User's password
                  role:
                    type: string
                    enum: [Approver, Maker]
                    description: User's role (Approver or Maker)
                required:
                  - username
                  - password
                  - role
        responses:
          '200':
            description: User successfully registered
            content:
              application/json:
                example:
                  message: User successfully registered
                  data:
                    _id: "5f8a5f7a4b56a6778c1a2345"
                    username: SH-Test
                    role: Maker
          '400':
            description: Bad request
            content:
              application/json:
                example:
                  error: Invalid role..! Available Roles = Approver or Maker.
          '500':
            description: Internal server error
            content:
              application/json:
                example:
                  error: Invalid Register Request..!!

  /api/users/login:
    post:
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: User's username
                password:
                  type: string
                  description: User's password
              required:
                - username
                - password
      responses:
        '200':
          description: User successfully logged in
          content:
            application/json:
              example:
                message: SH-Test Successfully logged in as Maker
                data: jwt_token_here
        '400':
          description: Bad request or incorrect password
          content:
            application/json:
              example:
                error: Password is incorrect
        '500':
          description: Internal server error
          content:
            application/json:
              example:
                error: An error occurred while logging in